function random_logo(){
var randomlogo=new Array()
//heres all the randomized "logos"
randomlogo[1]="&#x1F4A4; beep beep lettuce" 			//ZZZ
randomlogo[2]="&#x1F44C; beep beep lettuce"				//okhand
randomlogo[3]="&#x1F349; beep beep lettuce"				//melon
randomlogo[4]="&#x1F36A; beep beep lettuce"				//cookie
randomlogo[5]="&#x1F35A; beep beep lettuce"				//rice
randomlogo[6]="&#x1F95E; beep beep lettuce"				//pancakes
randomlogo[7]="&#x1F957; beep beep salad"				//salad
randomlogo[8]="&#x1F5BC; beep beep lettuce"				//catpicture
randomlogo[9]="&#x1F389; beep beep lettuce"				//party
randomlogo[10]="&#x1F388; beep beep lettuce"			//balloon
randomlogo[11]="&#x1F3B2; beep beep lettuce"			//dice
randomlogo[12]="&#x1F5D1; beep beep lettuce"			//trash
randomlogo[13]="&#x1F171;eep &#x1F171;eep &#x1F171;ettuce"			//B
randomlogo[14]="&#x1F408; beep beep lettuce"			//cat
randomlogo[15]="&#x1F984; beep beep lettuce"			//unicorn
randomlogo[16]="&#x1F986; beep beep lettuce"			//duck
randomlogo[17]="&#x1F40D; beep beep lettuce"			//snek
randomlogo[18]="&#x1F422; beep beep lettuce"			//turt
randomlogo[19]="&#x1F41F; beep beep lettuce"			//fish
randomlogo[20]="OwO what's this?"						//i hope noone sees this
randomlogo[21]="vincent wuz here xd"					//vincent was here
randomlogo[22]="&#x1F914; beep beep lettuce"			//thinking
randomlogo[23]="&#x1F6CC; beep beep lettuce"			//bed
randomlogo[24]="beep&#x1F44F;beep&#x1F44F;lettuce"			//clap
randomlogo[25]="&#x1F40E; beep beep lettuce"			//hoers
randomlogo[26]="&#x1F414; beep beep lettuce"			//chikun
randomlogo[27]="&#x1F424; beep beep lettuce"			//chik
randomlogo[28]="&#x1F42C; beep beep lettuce"			//dolphin
randomlogo[29]="&#x1F41D;&#x1F41D;&#x1F41D;&#x1F41D;&#x1F41D;"		//bees
randomlogo[30]="&#x1F333; beep beep lettuce"			//tree
randomlogo[31]="&#x1F34B; beep beep lettuce"			//lemon
randomlogo[32]="&#x1F344; beep beep lettuce"			//mushroom
randomlogo[33]="&#x1F35E; beep beep lettuce"			//bread
randomlogo[34]="&#x1F355; beep beep lettuce"			//pizza
randomlogo[35]="&#x1F363; ビープ ビープ レタス"				//japanese
randomlogo[36]="&#x1F366; beep beep lettuce"			//ice cream
randomlogo[37]="&#x1F382; don't believe its lies"			//cake
randomlogo[38]="&#x1F36B; beep beep lettuce"			//chocolate
randomlogo[39]="&#x1F36D; beep beep lettuce"			//lollipop
randomlogo[40]="&#x2615; beep beep lettuce"				//coffee
randomlogo[41]="&#x1F30E; beep beep lettuce"			//world
randomlogo[42]="&#x1F3E1; beep beep lettuce"			//house
randomlogo[43]="&#x1F303; beep beep lettuce"			//city
randomlogo[44]="&#x1F3A1; beep beep lettuce"			//ferris wheel
randomlogo[45]="&#x1F3A8; beep beep lettuce"			//paint
randomlogo[46]="&#x1F682;&#x1F683;&#x1F683;&#x1F683;&#x1F683;&#x1F683;"		//train
randomlogo[47]="&#x1F697; beep beep lettuce"			//car
randomlogo[48]="beep beep lettuce"			//no logo
randomlogo[49]="&#x1F6D1; it's time to stop"			//stop
randomlogo[50]="&#x26F5; beep beep lettuce"				//boat
randomlogo[51]="&#x2601; beep beep lettuce"				//cloud
randomlogo[52]="&#x26C5; beep beep lettuce"				//sun/cloud
randomlogo[53]="&#x1F308; beep beep lettuce"			//rainbow
randomlogo[54]="&#x1F381; beep beep lettuce"			//gift
randomlogo[55]="&#x1F3B7; beep beep lettuce"			//sax
randomlogo[56]="&#x1F4BB; beep beep lettuce"			//computer
randomlogo[57]="OH HELLO THERE"							//swamp
randomlogo[58]="&#x1F4A1; beep beep lettuce"			//light
randomlogo[59]="&#x1F4DA; beep beep lettuce"			//books
randomlogo[60]="&#x1F4DC; beep beep lettuce"			//scroll
randomlogo[61]="&#x1F58D; beep beep lettuce"			//crayon
randomlogo[62]="&#x1F3F9; beep beep lettuce"			//bow
randomlogo[63]="&#x2714; beep beep lettuce"				//check
randomlogo[64]="[insert logo] beep beep lettuce"		//text
randomlogo[65]="ǝɔnʇʇǝl dǝǝq dǝǝq"						//upside down
randomlogo[66]="b͖͕̗̳̖̩ͪ̂ͭͮ̀ͅe̶̙̺͙̰̫̤̻̾͌̋̂͑͂͑eṗ̧͚̟͕̳̣̟͆͆̍ ͗ͬ͗̈́͒͠b͉̗̜̜̓͂̒̎̉̊ͩ͞e̝̚e̷̻̖̟͌p̸̮̟͔̦ͪ̎́ͮͥ̃̑ ͨ̊͗̇̑̚͏̰̹̪l̝̳̟̩e̙̬͎͠t̰͔̠̦̩́ͤt̪̺̗͚͚͓̗ͬ́̈́͌̊͑͊u̬̮̣̞̜͆̎͒ͭ͡c̛͕̙̲̟̫̪̏ͨ̓̍̈ͩͅe̻̙̙͔͖̞͊ͨ̾ͦͧ͝"			//zalgo
randomlogo[67]="b͔͉̟̹̰e̘͛̈̎̽̅ͫȩ̤͇̼͋p̀̅҉̦͈̲͔̤̟̭ ̝͔͢b̴ͥͭ̈́́͋̽̆e̱͔̯ͨ̅̀e͓͙ͥ̎̕p̾̐͆̓҉͖̺̗͕̜͖ ̟̹̫͊͋̃ͧͭl̇ͮḙ̷̤̹̿ͤ̈́̓t̶̬͇͙̿͆ͮͣ͗̚t̥͖͖͎̒̓ͧ̂ͤ̚u̘̽ͬ̃͐̈̀ć͙̞̜̇ͩ͂̇͝e̻̓"			//zalgo2
randomlogo[68]="haha nice"								//nice
randomlogo[69]="ｂ ｅ ｅ ｐ　ｂ ｅ ｅ ｐ　ｌ ｅ ｔ ｔ ｕ ｃ ｅ"		//aesthetic
var ry=Math.floor(Math.random()*randomlogo.length)
if (ry==0)
ry=1
document.write('<p>'+randomlogo[ry]+'</p>')
}
random_logo();